# Generated by Django 2.2.9 on 2020-04-23 14:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Department',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('department_name', models.CharField(max_length=200)),
                ('department_description', models.CharField(max_length=200)),
                ('department_created_at', models.DateTimeField(auto_now=True)),
                ('department_short_name', models.CharField(max_length=200)),
            ],
            options={
                'verbose_name_plural': 'Department',
            },
        ),
        migrations.CreateModel(
            name='Semester',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('semester_name', models.CharField(max_length=200)),
                ('semester_created_at', models.DateTimeField(auto_now=True)),
                ('department_id', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='books.Department')),
            ],
            options={
                'verbose_name_plural': 'Semester',
            },
        ),
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('course_name', models.CharField(max_length=200)),
                ('course_description', models.CharField(max_length=200)),
                ('course_created_at', models.DateTimeField(auto_now=True)),
                ('course_code', models.CharField(help_text='eg. CSE0000', max_length=200)),
                ('semester_name', models.ForeignKey(default='S', on_delete=django.db.models.deletion.CASCADE, to='books.Semester')),
            ],
            options={
                'verbose_name_plural': 'Courses',
            },
        ),
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('book_name', models.CharField(max_length=200)),
                ('book_file', models.FileField(upload_to='books/')),
                ('course_id', models.ForeignKey(default='C', on_delete=django.db.models.deletion.CASCADE, to='books.Course')),
            ],
            options={
                'verbose_name_plural': 'Books',
            },
        ),
    ]
