# Generated by Django 2.2.9 on 2020-04-26 04:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0002_auto_20200426_0359'),
    ]

    operations = [
        migrations.RenameField(
            model_name='book',
            old_name='course_code_id',
            new_name='course_code',
        ),
    ]
