# Generated by Django 2.2.9 on 2020-04-10 05:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tutor', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='tutorial',
            name='slug',
            field=models.SlugField(default='likes', max_length=120),
        ),
    ]
