# Generated by Django 2.2.9 on 2020-04-06 09:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tutor', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='tutorial',
            name='pub_date',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
