# Generated by Django 2.2.9 on 2020-04-10 05:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tutor', '0002_tutorial_slug'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tutorial',
            name='slug',
        ),
    ]
