# Generated by Django 2.2.9 on 2020-04-06 11:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tutor', '0002_tutorial_pub_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='course_created_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='department',
            name='department_created_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
