# Generated by Django 2.2.9 on 2020-04-07 13:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tutor', '0003_auto_20200406_1143'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='department_name',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='tutor.Department'),
        ),
        migrations.AlterField(
            model_name='tutorial',
            name='course_name',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='tutor.Course'),
        ),
    ]
